provider:
  name: openfaas

functions:
  bcrypt:
    lang: golang-middleware
    handler: ./bcrypt
    image: ghcr.io/${OWNER:-alexellis}/bcrypt:${TAG:-latest}
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 10
      com.openfaas.scale.target: 500
      com.openfaas.scale.type: cpu

      com.openfaas.scale.zero: true
      com.openfaas.scale.zero-duration: 2m

      com.openfaas.git-branch: master
      com.openfaas.git-owner: ${OWNER:-alexellis}
      com.openfaas.git-repo: autoscaling-functions
      com.openfaas.git-sha: ${TAG:-4089a5f18b0692833e28a88d9ca263a68c329034}

    annotations:
      com.openfaas.git-repo-url: https://github.com/${OWNER:-alexellis}/autoscaling-functions
      github: true

  cows:
    skip_build: true
    image: ghcr.io/openfaas/cows:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 10
      com.openfaas.scale.target: 50
      com.openfaas.scale.type: rps

      com.openfaas.scale.zero: true
      com.openfaas.scale.zero-duration: 5m

      com.openfaas.git-branch: master
      com.openfaas.git-owner: openfaas
      com.openfaas.git-repo: store-functions
      com.openfaas.git-sha: ${TAG:-4089a5f18b0692833e28a88d9ca263a68c329034}
    annotations:
      com.openfaas.git-repo-url: https://github.com/openfaas/store-functions
      github: true

  sleep:
    skip_build: true
    image: ghcr.io/openfaas/sleep:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 10
      com.openfaas.scale.target: 5
      com.openfaas.scale.target-proportion: 0.8
      com.openfaas.scale.type: capacity

      com.openfaas.git-branch: master
      com.openfaas.git-owner: openfaas
      com.openfaas.git-repo: store-functions
      com.openfaas.git-sha: ${TAG:-4089a5f18b0692833e28a88d9ca263a68c329034}
    annotations:
      com.openfaas.git-repo-url: https://github.com/openfaas/store-functions
      github: true
    environment:
      sleep_duration: 1s

configuration:
  templates:
    - name: golang-middleware
